
package webinterface;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import webservice.FreelancerAccessPointService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-27T21:13:16.129+02:00
 * Generated source version: 3.5.1
 *
 */
public final class IFreelancerAccessPoint_FreelancerAccessPointPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice/", "FreelancerAccessPointService");

    private IFreelancerAccessPoint_FreelancerAccessPointPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FreelancerAccessPointService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        FreelancerAccessPointService ss = new FreelancerAccessPointService(wsdlURL, SERVICE_NAME);
        IFreelancerAccessPoint port = ss.getFreelancerAccessPointPort();

        {
        System.out.println("Invoking getByJobType...");
        java.lang.String _getByJobType_arg0 = "knitting";
        java.util.List<java.lang.String> _getByJobType__return = port.getByJobType(_getByJobType_arg0);
        System.out.println("getByJobType.result=" + _getByJobType__return);

        System.out.println("Invoking getFreelancerInfo...");
        webinterface.FreelancerInfo _getFreelancerInfo__return = port.getFreelancerInfo(_getByJobType__return.get(0));
        System.out.println("getFreelancerInfo.result=" + _getFreelancerInfo__return);


        }

        System.exit(0);
    }

}
