package webinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-27T21:13:16.174+02:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "http://webinterface/", name = "IFreelancerAccessPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface IFreelancerAccessPoint {

    @WebMethod(operationName = "GetByJobType", action = "urn:GetByJobType")
    @RequestWrapper(localName = "GetByJobType", targetNamespace = "http://webinterface/", className = "webinterface.GetByJobType")
    @ResponseWrapper(localName = "GetByJobTypeResponse", targetNamespace = "http://webinterface/", className = "webinterface.GetByJobTypeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getByJobType(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod(operationName = "GetFreelancerInfo", action = "urn:GetFreelancerInfo")
    @RequestWrapper(localName = "GetFreelancerInfo", targetNamespace = "http://webinterface/", className = "webinterface.GetFreelancerInfo")
    @ResponseWrapper(localName = "GetFreelancerInfoResponse", targetNamespace = "http://webinterface/", className = "webinterface.GetFreelancerInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public webinterface.FreelancerInfo getFreelancerInfo(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
