package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import webinterface.IFreelancerAccessPoint;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-27T21:13:16.179+02:00
 * Generated source version: 3.5.1
 *
 */
@WebServiceClient(name = "FreelancerAccessPointService",
                  wsdlLocation = "http://localhost:8080/Server/wsdl/freelanceraccesspoint.wsdl",
                  targetNamespace = "http://webservice/")
public class FreelancerAccessPointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice/", "FreelancerAccessPointService");
    public final static QName FreelancerAccessPointPort = new QName("http://webservice/", "FreelancerAccessPointPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Server/wsdl/freelanceraccesspoint.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FreelancerAccessPointService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Server/wsdl/freelanceraccesspoint.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FreelancerAccessPointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FreelancerAccessPointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FreelancerAccessPointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FreelancerAccessPointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FreelancerAccessPointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FreelancerAccessPointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IFreelancerAccessPoint
     */
    @WebEndpoint(name = "FreelancerAccessPointPort")
    public IFreelancerAccessPoint getFreelancerAccessPointPort() {
        return super.getPort(FreelancerAccessPointPort, IFreelancerAccessPoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFreelancerAccessPoint
     */
    @WebEndpoint(name = "FreelancerAccessPointPort")
    public IFreelancerAccessPoint getFreelancerAccessPointPort(WebServiceFeature... features) {
        return super.getPort(FreelancerAccessPointPort, IFreelancerAccessPoint.class, features);
    }

}
