
package webinterface.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.1
 * Sun Mar 27 21:09:01 CEST 2022
 * Generated source version: 3.5.1
 */

@XmlRootElement(name = "GetFreelancerInfoResponse", namespace = "http://webinterface/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetFreelancerInfoResponse", namespace = "http://webinterface/")

public class GetFreelancerInfoResponse {

    @XmlElement(name = "return", namespace = "http://webinterface/")
    private webservice.FreelancerInfo _return;

    public webservice.FreelancerInfo getReturn() {
        return this._return;
    }

    public void setReturn(webservice.FreelancerInfo new_return)  {
        this._return = new_return;
    }

}

